---

- name: install postfix
  ansible.builtin.package:
    name: postfix

- name: get installed version
  ansible.builtin.package_facts:
    manager: auto

- name: set installed version fact
  ansible.builtin.set_fact:
    __postfix_installed_version: >-
      {{ ansible_facts.packages['postfix'].0.version }}

- name: remove sendmail
  ansible.builtin.package:
    name: sendmail
    state: absent

- name: check if inet_interfaces will change
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces = '
    line: 'inet_interfaces = {{ postfix_inet_interfaces | join(", ") }}'
  check_mode: yes
  register: __postfix_inet_interfaces_precheck

- name: set needs restart fact
  ansible.builtin.set_fact:
    __postfix_needs_restart: '{{ __postfix_inet_interfaces_precheck.changed }}'

- name: configure main.cf
  ansible.builtin.template:
    src: '{{ lookup("first_found", __postfix_main_cf_templates) }}'
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  register: __postfix_main_configuration

- name: reload postfix service
  ansible.builtin.service:
    name: postfix
    state: reloaded
  when:
    - __postfix_main_configuration.changed
    - not __postfix_needs_restart

- name: restart postfix service
  ansible.builtin.service:
    name: postfix
    state: restarted
  when:
    - __postfix_main_configuration.changed
    - __postfix_needs_restart

- name: configure /etc/aliases
  ansible.builtin.template:
    src: '{{ lookup("first_found", __postfix_aliases_templates) }}'
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  register: __postfix_aliases_configuration

- name: regenerate /etc/aliases.db # noqa no-handler
  ansible.builtin.command: newaliases
  changed_when: yes
  when: __postfix_aliases_configuration.changed

- name: header_checks
  when: postfix_header_checks is defined
  block:

    - name: configure header_checks files
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: 0644
      when: item.content is defined
      register: __postfix_header_checks_configuration
      loop: '{{ postfix_header_checks }}'

    - name: regenerate header_checks files
      ansible.builtin.command: 'postmap {{ item.item.dest }}'
      changed_when: yes
      when:
        - item.changed
        - >-
          item.item.type == "btree" or
          item.item.type == "cdb" or
          item.item.type == "dbm" or
          item.item.type == "hash" or
          item.item.type == "lmdb" or
          item.item.type == "sdbm"
      loop: '{{ __postfix_header_checks_configuration.results }}'

- name: canonical_maps
  when: postfix_canonical is defined
  block:

    - name: configure canonical_maps files
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: 0644
      when: item.content is defined
      register: __postfix_canonical_configuration
      loop: '{{ postfix_canonical }}'

    - name: regenerate canonical_maps files
      ansible.builtin.command: 'postmap {{ item.item.dest }}'
      changed_when: yes
      when:
        - item.changed
        - >-
          item.item.type == "btree" or
          item.item.type == "cdb" or
          item.item.type == "dbm" or
          item.item.type == "hash" or
          item.item.type == "lmdb" or
          item.item.type == "sdbm"
      loop: '{{ __postfix_canonical_configuration.results }}'

- name: recipient_canonical_maps
  when: postfix_recipient_canonical is defined
  block:

    - name: configure recipient_canonical_maps files
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: 0644
      when: item.content is defined
      register: __postfix_recipient_canonical_configuration
      loop: '{{ postfix_recipient_canonical }}'

    - name: regenerate recipient_canonical_maps files
      ansible.builtin.command: 'postmap {{ item.item.dest }}'
      changed_when: yes
      when:
        - item.changed
        - >-
          item.item.type == "btree" or
          item.item.type == "cdb" or
          item.item.type == "dbm" or
          item.item.type == "hash" or
          item.item.type == "lmdb" or
          item.item.type == "sdbm"
      loop: '{{ __postfix_recipient_canonical_configuration.results }}'

- name: sender_canonical_maps
  when: postfix_sender_canonical is defined
  block:

    - name: configure sender_canonical_maps files
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: 0644
      when: item.content is defined
      register: __postfix_sender_canonical_configuration
      loop: '{{ postfix_sender_canonical }}'

    - name: regenerate sender_canonical_maps files
      ansible.builtin.command: 'postmap {{ item.item.dest }}'
      changed_when: yes
      when:
        - item.changed
        - >-
          item.item.type == "btree" or
          item.item.type == "cdb" or
          item.item.type == "dbm" or
          item.item.type == "hash" or
          item.item.type == "lmdb" or
          item.item.type == "sdbm"
      loop: '{{ __postfix_sender_canonical_configuration.results }}'

- name: smtp_generic_maps
  when: postfix_smtp_generic is defined
  block:

    - name: configure smtp_generic_maps files
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: 0644
      when: item.content is defined
      register: __postfix_smtp_generic_configuration
      loop: '{{ postfix_smtp_generic }}'

    - name: regenerate smtp_generic_maps files
      ansible.builtin.command: 'postmap {{ item.item.dest }}'
      changed_when: yes
      when:
        - item.changed
        - >-
          item.item.type == "btree" or
          item.item.type == "cdb" or
          item.item.type == "dbm" or
          item.item.type == "hash" or
          item.item.type == "lmdb" or
          item.item.type == "sdbm"
      loop: '{{ __postfix_smtp_generic_configuration.results }}'

- name: transport_maps
  when: postfix_transport is defined
  block:

    - name: configure transport_maps files
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: 0644
      when: item.content is defined
      register: __postfix_transport_configuration
      loop: '{{ postfix_transport }}'

    - name: regenerate transport_maps files
      ansible.builtin.command: 'postmap {{ item.item.dest }}'
      changed_when: yes
      when:
        - item.changed
        - >-
          item.item.type == "btree" or
          item.item.type == "cdb" or
          item.item.type == "dbm" or
          item.item.type == "hash" or
          item.item.type == "lmdb" or
          item.item.type == "sdbm"
      loop: '{{ __postfix_transport_configuration.results }}'

- name: enable postfix service and assure it is started
  ansible.builtin.service:
    name: postfix
    enabled: yes
    state: started
  tags:
    - service

...
