---

- name: verify
  hosts: all
  tasks:

    # -------------------------------------------------------------------------
    # check package
    # -------------------------------------------------------------------------

    - name: check package installation
      ansible.builtin.package:
        name: postfix
        state: present
      check_mode: yes
      register: __postfix_installed

    - name: debug package installation
      ansible.builtin.debug:
        var: __postfix_installed

    - name: assert on package installation
      ansible.builtin.assert:
        that:
          - not __postfix_installed.failed
          - not __postfix_installed.changed
        success_msg: 'package is installed'

    # -------------------------------------------------------------------------
    # check service
    # -------------------------------------------------------------------------

    - name: check service
      ansible.builtin.service:
        name: postfix
        enabled: yes
        state: started
      check_mode: yes
      register: __postfix_service

    - name: debug service
      ansible.builtin.debug:
        var: __postfix_service

    - name: assert on service
      ansible.builtin.assert:
        that:
          - not __postfix_service.failed
          - not __postfix_service.changed
          - __postfix_service.state == 'started'
          - __postfix_service.enabled
        success_msg: 'service is both enabled and started'

...
